name: Auto Build, PR and Merge

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      hugoVersion:
        description: "Hugo Version"
        required: false
        default: "0.128.0"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  merge-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set up Git configuration
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git config credential.helper 'store'
          echo "https://${{ secrets.PAT_TOKEN }}@github.com" > ~/.git-credentials

      - name: Merge dev into main with conflict resolution
        run: |
          git fetch origin main
          git checkout main
          git merge origin/dev --no-ff --allow-unrelated-histories -X theirs -m "Auto-merging dev into main"
          git push origin main

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${{ github.event.inputs.hugoVersion || '0.128.0' }}/hugo_extended_${{ github.event.inputs.hugoVersion || '0.128.0' }}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: recursive
          fetch-depth: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: America/Los_Angeles
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Find and close PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=$(gh pr list --state open --base main --head dev --json number -q '.[0].number')
          if [ -n "$pr_number" ]; then
            gh pr close "$pr_number"
          else
            echo "No open PR found to close"
          fi
